### ISSUE TITLE
Resolve Dns Mode show blank

### ISSUE THREAD

**Issue by crackself** [zaion520/luci-app-rss#2]
is that I missing some depend package?
![2](https://user-images.githubusercontent.com/16448332/27443248-01b166b0-57a5-11e7-9aaf-3eb119eae86b.png)

**Comment by zaion520** [comment]
This is just a Luci, and you need to compile pdnsd or pcap_dnsproxy  dns2socks  dnsproxy and 
ssr https://github.com/kuoruan/openwrt-shadowsocksr

**Comment by crackself** [comment]
try to complie pcap_dnsproxy and dns2socks dnsproxy(no support by offical,have to add source into package),all about them faile in CC(gargoyle),here is errors outut

pcap-dnsproxy-0.4.9.0/Source/Pcap_DNSProxy/Base.cpp:20:
/home/crackself/gargoyle/ar71xx-src/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.9.0/Source/Pcap_DNSProxy/Platform.h:505:21: fatal error: sodium.h: No such file or directory
  #include <sodium.h>
                     ^
compilation terminated.
Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/build.make:57: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o' failed
make[6]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o] Error 1make[6]: Leaving directory '/home/crackself/gargoyle/ar71xx-src/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.9.0'
CMakeFiles/Makefile2:78: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[5]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
make[5]: Leaving directory '/home/crackself/gargoyle/ar71xx-src/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.9.0'
Makefile:116: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/crackself/gargoyle/ar71xx-src/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.9.0'
Makefile:176: recipe for target '/home/crackself/gargoyle/ar71xx-src/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.9.0/.built' failed
make[3]: *** [/home/crackself/gargoyle/ar71xx-src/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.9.0/.built] Error 2
make[3]: Leaving directory '/home/crackself/gargoyle/ar71xx-src/package/pcap-dnsproxy'
package/Makefile:191: recipe for target 'package/pcap-dnsproxy/compile' failed
make[2]: *** [package/pcap-dnsproxy/compile] Error 2
make[2]: Leaving directory '/home/crackself/gargoyle/ar71xx-src'
package/Makefile:188: recipe for target '/home/crackself/gargoyle/ar71xx-src/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/crackself/gargoyle/ar71xx-src/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/crackself/gargoyle/ar71xx-src'
/home/crackself/gargoyle/ar71xx-src/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by zaion520** [comment]
不知道石像鬼 ,但是CC编译可以通过  
ar71xx dns解析以编译好 https://github.com/zaion520/luci-app-rss/releases/tag/openwrtCC
