### ISSUE TITLE
很喜欢这个ss

### ISSUE THREAD

**Issue by fuqiang03** [zaion520/luci-app-rss#3]
大神可否添加ss 服务端配置页面  
重新整理一下make文件
里面的文件看的我好乱
最好在添加多些的解析方式

**Comment by fuqiang03** [comment]
列表模式依然无效，求帮助

**Comment by zaion520** [comment]
@fuqiang03 什么列表模式不能用?GFW?  dns解析常用的都在有了吧,

**Comment by fuqiang03** [comment]
GFW列表不能用，dns解析正常使用，主页的国内外的线路连通显示有时候回不准确

**Comment by zaion520** [comment]
我就用gfw,很正常啊,主页显示也正常,有可能线路问题导致连不通而已

**Comment by fuqiang03** [comment]
恩，明天我会发送详细的图片

**Comment by zaion520** [comment]
@fuqiang03 haode

**Comment by fuqiang03** [comment]
![qq 20170630201110](https://user-images.githubusercontent.com/26851715/27735359-b23294be-5dd1-11e7-8dc0-aaacbed0b165.png)
![qq 20170630201134](https://user-images.githubusercontent.com/26851715/27735358-b2327178-5dd1-11e7-8a4b-a200141b6422.png)
![qq 20170630195733](https://user-images.githubusercontent.com/26851715/27735360-b236500e-5dd1-11e7-9a87-e925d85502ca.png)
现在显示连接状态 但是依然无法访问

**Comment by fuqiang03** [comment]
其他模式都能正常工作

**Comment by fuqiang03** [comment]
![qq 20170630205119](https://user-images.githubusercontent.com/26851715/27736354-6847a600-5dd6-11e7-8b69-f261ef510b5f.png)
连接显示国外断开 但是确可以正常访问

**Comment by fuqiang03** [comment]
![qq 20170630205450](https://user-images.githubusercontent.com/26851715/27736409-ab1c0c3c-5dd6-11e7-8ec8-1f607402e602.png)

**Comment by zaion520** [comment]
![image](https://github.com/zaion520/CHN/blob/master/TIM%E5%9B%BE%E7%89%8720170701171857.png)

**Comment by zaion520** [comment]
![tim 20170701171857](https://user-images.githubusercontent.com/25002708/27760862-20e61324-5e84-11e7-918f-b1bcb3b99a58.png)
@fuqiang03

**Comment by zaion520** [comment]
![Uploading TIM图片20170701174046.png…]()

**Comment by fuqiang03** [comment]
![qq 20170701194410](https://user-images.githubusercontent.com/26851715/27761796-f82585f2-5e95-11e7-801c-fb6532bd25fc.png)
我这个算是连上了吗

**Comment by fuqiang03** [comment]
找到原因了 我自己固定了 dns 没有走路由器dns
谢谢

**Comment by fuqiang03** [comment]
![qq 20170701220630](https://user-images.githubusercontent.com/26851715/27762721-001e25d4-5eaa-11e7-8510-c6847b1f4633.png)
![qq 20170701220622](https://user-images.githubusercontent.com/26851715/27762722-001f1188-5eaa-11e7-96a9-1cf00a8f6986.png)

**Comment by fuqiang03** [comment]
![qq 20170701232026](https://user-images.githubusercontent.com/26851715/27763331-508ed2a2-5eb4-11e7-8b25-b9ad1fa94748.png)
